<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="5" name="Listener Test Case" time="0.058" errors="0" timestamp="2025-01-27T21:46:23 IST">
  <testcase classname="com.testNG.listeners.SampleTest" name="testFour" time="0.005">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.testNG.listeners.SampleTest" name="testGetData" time="0.002"/>
  <testcase classname="com.testNG.listeners.SampleTest" name="testGetData" time="0.0"/>
  <testcase classname="com.testNG.listeners.SampleTest" name="testOne" time="0.002"/>
  <testcase classname="com.testNG.listeners.SampleTest" name="testThree" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at com.testNG.listeners.SampleTest.testThree(SampleTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener Test Case -->
